// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

// Thing defines model for Thing.
type Thing struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
