openapi: 3.1.1

info:
  title: Cycas API
  version: 0.0.1

servers:
  - url: http://localhost:8080

paths:
  /v1/things/{thingId}:
    get:
      parameters:
        - name: thingId
          in: path
          required: true
          schema:
            type: string

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Thing"

components:
  schemas:
    Thing:
      type: object
      required: [id, name]
      properties:
        id:
          type: string
        name:
          type: string
