openapi: 3.0.3

info:
  title: Cycas API
  version: 0.0.1

servers:
  - url: http://localhost:8000

paths:
  /v1/categories:
    post:
      operationId: createCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minLength: 3
                  maxLength: 32
                  pattern: "^[a-z](?:[a-z -]{1,30}[a-z])?$"

      responses:
        "201":
          description: Category created
          content:
            application/json:
              schema:
                type: object
                required:
                  - name
                  - id
                properties:
                  id:
                    type: string
                  name:
                    type: string

        "409":
          description: Category with name already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
