openapi: 3.0.3

info:
  title: Cycas API
  version: 0.0.1

servers:
  - url: http://localhost:8080

paths:
  /v1/categories:
    post:
      operationId: createCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string

      responses:
        "201":
          description: Category created
          content:
            application/json:
              schema:
                type: object
                required:
                  - name
                  - id
                properties:
                  id:
                    type: string
                  name:
                    type: string

        "409":
          description: Category with name already exists
          content:
            application/json:
              schema:
                type: string
